# -*- coding: utf-8 -*-
"""2025AB05070_MLAssignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fkqTO-sbTpESMUHdIR9w49HuXETtJqc
"""

# !pip install streamlit pyngrok xgboost

import streamlit as st
from model.logistic_regression import run_model as lr
from model.decision_tree import run_model as dt
from model.knn import run_model as knn
from model.naive_bayes import run_model as nb
from model.random_forest import run_model as rf
from model.xgboost_model import run_model as xgb

st.title("Breast Cancer Classification - ML Assignment 2")

data_path = "breast-cancer.csv"

model_choice = st.selectbox(
    "Select Model",
    ["Logistic Regression", "Decision Tree", "KNN",
     "Naive Bayes", "Random Forest", "XGBoost"]
)

if st.button("Run Model"):

    if model_choice == "Logistic Regression":
        results = lr(data_path)
    elif model_choice == "Decision Tree":
        results = dt(data_path)
    elif model_choice == "KNN":
        results = knn(data_path)
    elif model_choice == "Naive Bayes":
        results = nb(data_path)
    elif model_choice == "Random Forest":
        results = rf(data_path)
    else:
        results = xgb(data_path)

    st.subheader("Evaluation Metrics")

    for key, value in results.items():
        if key != "Confusion Matrix":
            st.write(f"{key}: {value}")

    st.subheader("Confusion Matrix")
    st.write(results["Confusion Matrix"])

"""# New Section"""